actionid: py34
msg: getenv
cmdargs: ['/home/frodo/Python-Projekte/.virtualenvs/pdf2textbox/.tox/py34/bin/pip', 'install', 'check-manifest', 'pytest', 'requests', 'pdfminer2', 'pytest-cov']

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting check-manifest
  Cache entry deserialization failed, entry ignored
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/check-manifest/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/check-manifest/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/check-manifest/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/check-manifest/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/check-manifest/
  Could not fetch URL https://pypi.python.org/simple/check-manifest/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/check-manifest/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement check-manifest (from versions: )
No matching distribution found for check-manifest
